# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f60c7535c77a8e0249ee4000b551a52dafff9ec1c40693924f6adb550e7c2aeee0b81bdf4b1883a4039d0db0d2f41670218bf952c6deda9af306b9ed59ecb11

test:
  secret_key_base: 85c5a4af7414faaeb15244764bd205c6f834243b1572f9109e214fda2f400a9409f24a0a80a4dc548ad3cafee181e70898669bf27561517c9a9f9371a1ce37ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
